### ISSUE TITLE
Missing events in DOMAttributes

### ISSUE THREAD

**Issue by chronoDave** [forgojs/forgo#100]
Events such as [beforeinput](https://developer.mozilla.org/en-US/docs/Web/API/Element/beforeinput_event), [focusin](https://developer.mozilla.org/en-US/docs/Web/API/Element/beforeinput_event) and [focusout](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event) are not available in `jsxTypes.ts`, making it difficult to work with these events when using TypeScript.

What's the rationale for including / excluding certain events in `DOMAttributes`?

**Comment by spiffytech** [comment]
The rationale is we grabbed a lot of that from... somewhere. Probably another framework, which ideally we'd remember & credit in that file.

And so we only have whatever our source included.

Feel free to source and PR a more up-to-date set of attributes.
