### ISSUE TITLE
handlerDisabledOnNodeDelete does not evaluate if forgo.deleted is undefined

### ISSUE THREAD

**Issue by chronoDave** [forgojs/forgo#101]
As mentioned in the title, `handlerDisabledOnNodeDelete` incorrectly does not evaluate when `node.__forgo.deleted` is undefined due to strict false checking.

As `undefined === false` returns `false`, `handlerDisabledOnNodeDelete` will not evaluate.

https://github.com/forgojs/forgo/blob/fbe7d28ad7b6d28d862e6f16e62cbf8df05649b9/src/index.ts#L445-L451

Unfortunately I'm unable to replicate this behaviour in CodeSandbox, but `node.__forgo.deleted` is typed as `boolean | undefined`.

https://github.com/forgojs/forgo/blob/fbe7d28ad7b6d28d862e6f16e62cbf8df05649b9/src/index.ts#L124-L130

**Comment by spiffytech** [comment]
4.1.6 published with your PR.
