### ISSUE TITLE
Where is build script?

### ISSUE THREAD

**Issue by Fl0pZz** [forgojs/forgo#2]
Where is build script?

https://github.com/forgojs/forgo/blob/main/package.json#L4

**Comment by DanielBoa** [comment]
If you run `npx tsc` the project will be compiled to `./dist`, this output folder is referenced in the tsconfig.

**Comment by jacob-ebey** [comment]
@Fl0pZz My PR here has an example of updated scripts: https://github.com/forgojs/forgo/pull/1

**Comment by jeswin** [comment]
I've added a "build" script to package.json, which just calls tsc. Not really useful in itself, but it could help avoid some confusion.
