### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by Fl0pZz** [forgojs/forgo#21]
Is this production ready? This library support ie10-ie11?

**Comment by jeswin** [comment]
Produciton readiness will have to wait till we hit v1 - which is expected in Feb.

It should support IE10-11 with the required polyfills, but again we probably won't get to it until after v1.

**Comment by jeswin** [comment]
FWIW, we're API stable now. We can keep this open till we hit V1.

**Comment by jeswin** [comment]
We just hit V1. 

There might still be bugs on account of it being just a couple of months old - but hopefully not many and it's 100% API stable.
I'll be happy to look into bugs/issues on priority if you find any.
