### ISSUE TITLE
SVG-family elements not receiving attrs

### ISSUE THREAD

**Issue by spiffytech** [forgojs/forgo#22]
If I copy/paste an SVG file into a Forgo component the elements get rendered, but their attrs are missing in my DevTools, so nothing is visible on my page.

[Sandbox](https://codesandbox.io/s/sleepy-cerf-q481s?file=/src/index.tsx)

**Comment by jeswin** [comment]
I'll look at it in just a bit.

**Comment by jeswin** [comment]
So, this is an interesting problem. Good find.

So far I've been setting attributes like this:

```js
node.someattr = value;
```

That works with HTML DOM elements but doesn't work for svg.

So I could do:
```js
node.setAttribute("prop", "value");
```

That causes the attributes to be visible in dev tools as expected (although I haven't been able to see anything yet on the screen). 

One challenge is how to decide on setAttribute vs directly setting the prop. Directly setting the prop is way faster (and recommended I think) for HTML DOM nodes - so we might have to retain that. But we'll have to detect svg/other markup and use setAttribute accordingly.

I'm looking into this.

**Comment by spiffytech** [comment]
Sounds tricky. I found a list of [all SVG tags](https://github.com/element-io/svg-tags/blob/master/lib/svg-tags.json), but that JSON file is a whopping 1KiB, way too much to tack onto Forgo. 

I wonder if there's a solution in tracking whether each element to render is ancestored by an SVG element? That could produce weird edge cases if e.g., someone used Forgo to create a custom element that rendered SVG fragments for non-Forgo tools to use. But for SVGs rendered entirely inside Forgo, it sounds maybe promising?

I'm going to explore if there's a way to take the spirit of a bloom filter's set hashing (an online calculator suggests we could encode the whole SVG tag set in something around 95-100B). The hash can be precomputed and stored in git, we'd just need an algorithm that's KiB-cheap to code into Forgo. If possible, that'd get us guaranteed "this is an SVG tag" without storing the list of tags as expensive ASCII text. Paired with a `Set` to memoize tag checks it would be computationally efficient, too.

Or not if you don't want :D because that's a crazy complicated solution to bring to a problem this simple.

**Comment by spiffytech** [comment]
It looks like there are some attributes like `el.ownerSVGElement` that can clue us in, but all of that is unavailable if we don't create the element with `document.createElementNS('http://www.w3.org/2000/svg, tag)`, (which we should be doing) but that just brings us full-circle to detecting if a tag is part of SVG.

**Comment by spiffytech** [comment]
At a cursory glance it looks like React [assigns namespaces to every element](https://github.com/facebook/react/blob/9198a5cec0936a21a5ba194a22fcbac03eba5d1d/packages/react-dom/src/shared/DOMNamespaces.js), then derives the child's namespace from the parent. That gets us the behavior of my first suggestion. I think it wouldn't have the edge case I described, either - since we'd be checking the parent's XML-ness from the `<svg>` element's `xmlns` attribute, it doesn't matter if the parent element is a Forgo component or if Forgo is just playing a role in a larger app. 

Seems like a good way to go to me? Should be just a few lines to implement, and no wonky bloom filter logic.

**Comment by spiffytech** [comment]
It's also worth noting that [custom elements don't automatically reflect properties to attributes](https://alligator.io/web-components/attributes-properties/). They can and should, but setting properties could potentially make Forgo incompatible with some in-the-wild custom elements.

**Comment by jeswin** [comment]
Wow! Thanks for the thorough research. 

> Seems like a good way to go to me? Should be just a few lines to implement, no wonky bloom filter logic, and using createElementNS fixes the related bug that Forgo users will expect SVG refs to have SVG-related built-in attrs/methods.

I think this is an excellent idea. Let me see if I can get this to work.

> It's also worth noting that custom elements don't automatically reflect properties to attributes. They can and should, but setting properties could potentially make Forgo incompatible with some in-the-wild custom elements.

>  It looks like there are some simple ways to detect custom elements. Maybe check if SVG, check if custom element, check if attr is ARIA, and just play whack-a-mole with bugs that arise from the perf optimization?

I agree. That's what I'm gonna try now.

> So yeah, the perf improvement seems important from this cursory informal unscientific probably-glaring-mistakes test.

Thanks for confirming the performance delta with an actual test. So yeah, we definitely need  both then.

**Comment by spiffytech** [comment]
An idea for attrs like ARIA: it looks like `getAttribute` is pretty fast, so maybe the first time Forgo renders a new tag:attr-key combination, it tries the property setter first, then does `getAttribute` to see if it can read back its change. Store in a `Map` a boolean of whether the attribute needs to use `setAttribute` or not. Then the runtime learns on the fly whether it can take the perf shortcut and devs don't have random bugs with attrs that don't get set right because we didn't special-case them yet.

![image](https://user-images.githubusercontent.com/77867/106684738-08606680-6595-11eb-8c51-b7b32ec51aa4.png)

**Comment by jeswin** [comment]
> An idea for attrs like ARIA: it looks like getAttribute is pretty fast, so maybe the first time Forgo renders a new tag:attr-key combination, it tries the property setter first, then does getAttribute to see if it can read back its change.

One problem is that the property names (and values) don't always map to the attribute name (and values). For example, checkbox.checked is a boolean prop, while attributes are strictly string ("checked") in this case. Also the case with input.defaultValue mapping to the value attribute, and some more mentioned here: https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html

**Comment by jeswin** [comment]
I am leaning towards your namespace suggestion, it seems to work pretty well. Namespace resolution for an element (via the namespaceURI prop) also seems pretty fast in my (very) naive benchmark - doing 10 million in 2.5 seconds. And from the React link you sent, we could handle svg and math namespaces for now.

Eventually, we'll find more corner cases - and the quirky parts of the spec will end up in forgo. I think we might have to live with that.

**Comment by jeswin** [comment]
I am also making an additional assumption that if the attribute name includes a hyphen and the value is a string, we'll use setAttribute() instead. Will have to rollback if there are properties with a hyphen in them. 

If that works, would this handle aria-* and data-*?

**Comment by jeswin** [comment]
svg works (with all the assumptions above :) on v0.0.42.

[Sandbox](https://codesandbox.io/s/optimistic-leaf-n7639)

Still haven't looked at custom elements.

**Comment by spiffytech** [comment]
> svg works (with all the assumptions above :) on v0.0.42.

Looks great, thanks! :tada: Apparently I copy/pasta'd my SVG file out of the terminal incorrectly. It looks more correct when I copy it afresh :)

> If that works, would this handle aria-* and data-*?

Yep.

I found [the section](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes) of the HTML spec on the rules for reflecting properties to/from attributes. The rules are full of jargon terms I haven't looked up yet, but at least that should tell us what to be on guard for.

**Comment by jeswin** [comment]
I'll go through it. This feature has come mostly out of your inputs and suggestions, thanks. 👍

**Comment by jeswin** [comment]
Will keep this open till we have custom elements supported/tested.

**Comment by jeswin** [comment]
Custom elements (both built-in elements and standalone elements) have been implemented in v0.0.59.
