### ISSUE TITLE
Forgo not compatible with jsxFactory TSX constructor?

### ISSUE THREAD

**Issue by spiffytech** [forgojs/forgo#23]
I tried using Forgo with ESBuild and Snowpack, and couldn't get them to work. As best as I can tell they don't support the TypeScript new `react-jsx`/`jsxImportSource` JSX constructor type, and I couldn't get Forgo to work with those bundlers using the classic `jsxFactory` setting. ESBuild seems to [use its own custom TypeScript parser](https://github.com/evanw/esbuild/blob/master/docs/architecture.md#typescript-parsing). Not sure what's up with Snowpack.

I don't know if this is a Forgo docs deficiency or a bug report, or if it's worth working on since I'll bet everything will support `react-jsx` within a year. And Parcel is okay for me right now. But with Forgo 1.0 looming, I figured I'd raise the compatibility gap for consideration.

**Comment by jeswin** [comment]
Good point. I haven't tried the other JSX factory mechanisms yet - react-jsx was simpler to implement. 

Let's take a call on this just before we hit V1. I'll keep this open.

**Comment by zb0t** [comment]
I was playing around with getting this to work with Snowpack and found I could use the `@snowpack/plugin-babel` to get it working.

`.babelrc`:
```
{
  "plugins": [
    ["@babel/plugin-transform-react-jsx", {
      "runtime": "automatic",
      "importSource": "forgo"
    }]
  ],
  "presets": [
    "@babel/preset-typescript"
  ]
}
```

`snowpack.config.js`:
```
/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  mount: {
    public: {url: "/", static: true},
    src: {url: "/dist"},
  },
  plugins: ["@snowpack/plugin-babel"],
  packageOptions: {
    knownEntrypoints: ["forgo/jsx-runtime"]
  },
};
```

`tsconfig.json`:
```
"compilerOptions": {
  "module": "esnext",
  "target": "esnext",
  "moduleResolution": "node",
  "jsx": "react-jsx",
  "jsxImportSource": "forgo",
}
```

**Comment by jeswin** [comment]
That's very helpful @zb0t, thanks. 

And good to know, I've only tried webpack and parcel myself.

**Comment by jeswin** [comment]
jsxFactory and jsxFragment are supported in v0.0.68. (Tested only with JS, I'm hoping TS should work.)
