### ISSUE TITLE
Removing an input with a placeholder adds a placeholder attr to its sibling

### ISSUE THREAD

**Issue by GormanFletcher** [forgojs/forgo#30]
[Reproduction](https://codesandbox.io/s/optimistic-hopper-bwunk)

When clicking the toggle, the first input is removed. This causes the second input to incorrectly receive a `placeholder` attribute, which contains the value `undefined`.

This seems to require the inputs to be wrapped in `<label>`s to reproduce.

**Comment by jeswin** [comment]
Thanks for the bug report and reproduction. I'll investigate and fix it right away.

**Comment by jeswin** [comment]
@GormanFletcher  Fixed in v1.2.1. Thanks.
