### ISSUE TITLE
Forgo removes DOM elements that were appended using DOM APIs

### ISSUE THREAD

**Issue by spiffytech** [forgojs/forgo#42]
[Reproduction](https://codesandbox.io/s/forgo-append-el-9mbs5?file=/src/index.tsx)

If I capture the `ref` for an element and mess with it using the DOM APIs, the next time the element rerenders Forgo removes my manually-added elements.

**Comment by spiffytech** [comment]
I can dig into this - it'll be a good opportunity to wrap my head around the component index stuff.

**Comment by spiffytech** [comment]
I figured out how to fix the basic case, where a consuming app renders a `<div>` and meddles with its children. That basically came down to only calling `node.remove()` if `getForgoState(node) !== undefined`. That'll take care of e.g., having Forgo create an element for D3 to render into. I've got a fix + tests for this, which I can PR after #33 settles.

The more complex case is when an app manually adds children somewhere in the middle of JSX elements. I'm not sure whether that's worth supporting at this point. It looks a bit more complicated to implement, the semantics of how elements get reordered during DOM reconcile becomes part of the API, and I don't know what the use case would be. This would have to be revisited if/when [allowing jQuery to manipulate rendered elements](https://github.com/forgojs/forgo/issues/39#issuecomment-1020745657) becomes a thing.

Thoughts?

**Comment by spiffytech** [comment]
Thanks for the explanation, that'll help.

It looks like #33 (key reordering) touches some of the same spots in code that this change will, so I'll hold off on implementing until #33 is wrapped up.

**Comment by jeswin** [comment]
I've taken another shot at fixing #33. Hope this is unblocked now.

**Comment by spiffytech** [comment]
I think I may finally have it! :smile: 

I've patched forgo to leave unmanaged nodes alone, and I've got tests to that effect, and the whole test suite passes.

I've got to clean up a bunch of WIP changes I did while debugging, and document the feature in the README, and then I'll post a PR.

**Comment by spiffytech** [comment]
Manual test is looking good!

![image](https://user-images.githubusercontent.com/77867/160294761-89eb8cff-04a7-4118-b09b-6591529e0a1a.png)
