### ISSUE TITLE
Any ideas on how to approach a "context"?

### ISSUE THREAD

**Issue by jacob-ebey** [forgojs/forgo#5]
Ok, I'm at the point that suspense is supported for SSR. This looks something like:

```jsx
let retry = 1;
const app = <App />;
let promises: Set<Promise<any>> = new Set();
const onError = (err: any) => {
  if (err && err.then) {
    promises.add(err);
  }
};

let html = renderToString(app, { pretty: true, onError });

while (promises.size > 0 && retry <= maxRetries) {
  console.log("RETRY", retry);
  console.log("PROMISES", promises);
  await Promise.all(Array.from(promises));
  retry++;
  promises = new Set();
  html = renderToString(app, { pretty: true, onError });
}
```

Now the question is how should we approach context? The specific use-case here is storeing data that was loaded via suspense on server in a global for the client to consume.

Any thoughts here?

**Comment by jeswin** [comment]
Do you think we should allow render to return a promise? I'm just throwing ideas to explore here - will have to explore performance implications etc.

**Comment by jacob-ebey** [comment]
A promised based render pipeline would get rid of the need for suspense patterns and would be a better solution in my opinion. A context pattern is needed no mater what though to collect data to relay to the client and hydrate from.

**Comment by jacob-ebey** [comment]
I'm closing this as context is solved with new ssr implementation and ctor args
