### ISSUE TITLE
Changing a component's root tag drops + recreates all children

### ISSUE THREAD

**Issue by spiffytech** [forgojs/forgo#51]
[Sandbox](https://codesandbox.io/s/forgo-dropping-stateful-elements-nfl313?file=/src/index.tsx)

While working on #47 I noticed that when a component's root tag changes, forgo drops and recreates all child nodes of the component. Anything stateful (inputs, web components, unmanaged nodes) will be wiped clean or lost.

We should copy all nodes over when creating a new node for a component, rather than trusting the render cycle to recreate everything. This procedure should blindly copy all children, to ensure we rehome any unmanaged nodes.

**Comment by jeswin** [comment]
Good idea. Let me also check if React does this.

**Comment by spiffytech** [comment]
Vue [doesn't preserve](https://codesandbox.io/s/new-microservice-h6lhr9?file=/src/App.vue) the input's contents either.

**Comment by jeswin** [comment]
Looks like React doesn't do it either - even when the child nodes have ids.  
[Sandbox](https://codesandbox.io/s/smoosh-tdd-88te2u?file=/src/App.js)

Not entirely sure if my sandbox is a valid example. But if it is, perhaps we shouldn't keep state as well?

**Comment by spiffytech** [comment]
Your sandbox looks valid to me.

I did a cursory search in React/Vue's Github issues and couldn't spot anything about this.

Thinking about this a bit more, I have a hypothesis on why they don't keep children:

Changing the root tag of a component is a special case of the general pattern of replacing one element with another. If your component's JSX replaced some random element with something else, you wouldn't expect the children to transfer just because the previous and current elements are both in the same position. And in the middle of your component's JSX (as opposed to the root), you likely changed tags for a semantically-significant reason. In that light, giving special behavior to the root tag doesn't make much sense.

Reinforcing this is the DOM's semantics leaking through the JSX abstraction: you can't change the tag of an existing element, you have to create a new element and remove the old one. Losing the children is the default behavior.

If nobody else is bothered by it then it's probably not an edge case worth considering. And keeping element replacement semantics consistent is a good reason to WONTFIX.
