### ISSUE TITLE
Make a create-forgo-app tool

### ISSUE THREAD

**Issue by jeswin** [forgojs/forgo#7]
Most people use Create-React-App to build the scaffolding - and it's indeed quite useful to have one for Forgo. It can also set up some best practices.

**Comment by jeswin** [comment]
This could be super simple - just clone template repos on github.com/forgojs and do an ```npm i``` after that.

Rules to identify the repos:
- The cloned repo url will be https://github.com/forgojs/forgo-template-{template}-{language}
- If template is not provided, then use https://github.com/forgojs/forgo-template-{language}
- If language is not provided, use "javascript".

```sh
# clone https://github.com/forgojs/forgo-template-javascript into the directory myapp
create-forgo-app myapp 
```

```sh
# clone https://github.com/forgojs/forgo-template-typescript into the directory myapp
create-forgo-app myapp -l typescript

# same as 
create-forgo-app myapp --lang typescript
```

```sh
# clone https://github.com/forgojs/forgo-template-todos-javascript into the directory myapp
create-forgo-app myapp -t todos

# same as
create-forgo-app myapp --template todos
```

```sh
# clone https://github.com/forgojs/forgo-template-todos-typescript into the directory myapp
create-forgo-app myapp -t todos -l typescript

# same as
create-forgo-app myapp --template todos --lang typescript
```

**Comment by spiffytech** [comment]
> This could be super simple - just clone template repos on github.com/forgojs and do an npm i after that.

Svelte uses the [degit](https://svelte.dev/blog/the-easiest-way-to-get-started#2_Use_degit) tool with template repositories in place of a dedicated command line tool. Would that plus a list of recommended templates on the website be enough for Forgo?

**Comment by jeswin** [comment]
That's a good suggestion. I've updated the README accordingly.

Will close this now. Thanks.
