### ISSUE TITLE
./dist/index.js does not exist

### ISSUE THREAD

**Issue by chronoDave** [forgojs/forgo#75]
When working with [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) I noticed that my forgo import didn't seem to want to resolve. When inspecting why, it seems that the `main` field in `package.json` points to `./dist/index.js` which does not exist when you download forgo via `npm i forgo`.

![image](https://user-images.githubusercontent.com/27073716/186987839-324a57a7-06af-4f10-b4f8-abc875e075f3.png)

Is it possible to update the `main` field to `./dist/forgo.min.js`? I'm not entirely sure if this breaks non-minified builds, however.

**Comment by spiffytech** [comment]
Yeah, I don't think it'll be a problem to do that. 

It [sounds like](https://nodejs.org/api/packages.html#package-entry-points) we could probably drop the `main` field entirely since we have the `exports` field. I'll set up a basic repro with `eslint-plugin-import` and see if that works.

**Comment by spiffytech** [comment]
This was released in v3.2.1.
